export enum ACTIONS {
  SET_IS_OPEN_HEADER = "SET_IS_OPEN_HEADER",
  SET_MAIL = "SET_MAIL",
  SET_PASSWORD = "SET_PASSWORD",
  SET_PASSWORD_CONFIRM = "SET_IS_VALID_PASSWORD_CONFIRM",
  SET_USER = "SET_USER",
  // RESET_PASSWORD = 'RESET_PASSWORD'
}
