export enum ACTIONS {
  SET_IS_OPEN_HEADER = "SET_IS_OPEN_HEADER",
  SET_IS_VALID_USER = "SET_IS_VALID_USER",
  SET_IS_VALID_PASSWORD = "SET_IS_VALID_PASSWORD",
  SET_IS_VALID_PASSWORD_CONFIRM = "SET_IS_VALID_PASSWORD_CONFIRM",
  SET_IS_VALID_MAIL = "SET_IS_VALID_MAIL",

  // loginReducer
  SET_MAIL = "SET_MAIL",
  SET_PASSWORD = "SET_PASSWORD",
  SET_PASSWORD_CONFIRM = "SET_IS_VALID_PASSWORD_CONFIRM",
  SET_USER = "SET_USER",
}
